[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Carta de Serviços"
authors = [{name = "DITI | SEA", email = "cartadeservicos@sea.sc.gov.br"}]
dynamic = ["version", "description"]
